version: '2'

services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: toppack
            MYSQL_USER: suresh
            MYSQL_PASSWORD: root
    slim:
        image: yennisuresh/toppack:05
        command: php -S 0.0.0.0:3000 -t public
        environment:
            docker: "true"
        depends_on:
        - mysql
        ports:
        - 3000:3000
        volumes:
        - .:/toppack
